.TH "TP4_Martin_Marguerat_Vincent_Schupbach.c" 3 "Mon Apr 26 2021" "TP4_Martin_Marguerat_Vincent_Schupbach" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TP4_Martin_Marguerat_Vincent_Schupbach.c
.SH SYNOPSIS
.br
.PP
\fC#include <msp430\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNBR_VAL\fP   15"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned char \fBtrouveMin\fP (unsigned char arrayIn[])"
.br
.ti -1c
.RI "unsigned char \fBtrouveMax\fP (unsigned char arrayIn[])"
.br
.ti -1c
.RI "unsigned char \fBcalculMoyenne\fP (unsigned char arrayIn[])"
.br
.ti -1c
.RI "void \fBclignotteLED\fP (unsigned char nbrClignottement)"
.br
.ti -1c
.RI "void \fBbubbleSort\fP (unsigned char arrayIn[])"
.br
.ti -1c
.RI "unsigned int \fBsommeVal\fP (unsigned char arrayIn[])"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NBR_VAL   15"

.PP
Definition at line 17 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void bubbleSort (unsigned char arrayIn[])"
Fonction permettant de trier un tableau grâce à l'algorithme du Bubble Sort (https://www.youtube.com/watch?v=lyZQPjUT5B4 et https://www.youtube.com/watch?v=xli_FI7CuzA) 
.PP
\fBParameters\fP
.RS 4
\fIarrayIn\fP tableau de NBR_VAL valeurs 
.RE
.PP

.PP
Definition at line 130 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.PP
Referenced by main()\&.
.SS "unsigned char calculMoyenne (unsigned char arrayIn[])"
Fonction calculant la moyenne des nombre dans un tableau 
.PP
\fBParameters\fP
.RS 4
\fIarrayIn\fP tableau de NBR_VAL valeurs 
.RE
.PP
\fBReturns\fP
.RS 4
Moyenne calculée arrondie à l'entier en dessous 
.RE
.PP

.PP
Definition at line 100 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.PP
Referenced by main()\&.
.SS "void clignotteLED (unsigned char nbrClignottement)"
Fonction faisait clignotter la led à une fréquence de 2Hz pour un nombre de fois défini 
.PP
\fBParameters\fP
.RS 4
\fInbrClignottement\fP nombre de fois que la LED doit s'allumer 
.RE
.PP

.PP
Definition at line 113 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.PP
Referenced by main()\&.
.SS "int main (void)"

.PP
Definition at line 30 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.PP
References bubbleSort(), calculMoyenne(), clignotteLED(), NBR_VAL, trouveMax(), and trouveMin()\&.
.SS "unsigned int sommeVal (unsigned char arrayIn[])"
Fonction calculant la somme de toutes les valeurs d'un tableau 
.PP
\fBParameters\fP
.RS 4
\fIarrayIn\fP tableau de NBR_VAL valeurs 
.RE
.PP
\fBReturns\fP
.RS 4
somme des valeurs du tableau 
.RE
.PP

.PP
Definition at line 154 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.SS "unsigned char trouveMax (unsigned char arrayIn[])"
Fonction cherchant la valeur la plus grande d'un tableau 
.PP
\fBParameters\fP
.RS 4
\fIarrayIn\fP tableau de NBR_VAL valeurs 
.RE
.PP
\fBReturns\fP
.RS 4
valeur max trouvée dans le tableau 
.RE
.PP

.PP
Definition at line 81 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.PP
Referenced by main()\&.
.SS "unsigned char trouveMin (unsigned char arrayIn[])"
Fonction cherchant la valeur la plus petite d'un tableau 
.PP
\fBParameters\fP
.RS 4
\fIarrayIn\fP tableau de NBR_VAL valeurs 
.RE
.PP
\fBReturns\fP
.RS 4
valeur min trouvée dans le tableau 
.RE
.PP

.PP
Definition at line 62 of file TP4_Martin_Marguerat_Vincent_Schupbach\&.c\&.
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TP4_Martin_Marguerat_Vincent_Schupbach from the source code\&.
