TP4_Martin_Marguerat_Vincent_Schupbach: TP4_Martin_Marguerat_Vincent_Schupbach.c File Reference
TP4_Martin_Marguerat_Vincent_Schupbach.c File Reference
#include <msp430.h>
#include <stdio.h>
#include <stdbool.h>
Macros
#define NBR_VAL 15
Functions
unsigned char trouveMin (unsigned char arrayIn[])
unsigned char trouveMax (unsigned char arrayIn[])
unsigned char calculMoyenne (unsigned char arrayIn[])
void clignotteLED (unsigned char nbrClignottement)
void bubbleSort (unsigned char arrayIn[])
unsigned int sommeVal (unsigned char arrayIn[])
int main (void)
Macro Definition Documentation
NBR_VAL
#define NBR_VAL 15
Definition at line 17 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
Function Documentation
bubbleSort()
void bubbleSort (unsigned char arrayIn[])
Fonction permettant de trier un tableau grâce à l'algorithme du Bubble Sort (https://www.youtube.com/watch?v=lyZQPjUT5B4 et https://www.youtube.com/watch?v=xli_FI7CuzA)
Parameters
arrayIn tableau de NBR_VAL valeurs
Definition at line 130 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
Referenced by main().
calculMoyenne()
unsigned char calculMoyenne (unsigned char arrayIn[])
Fonction calculant la moyenne des nombre dans un tableau
Parameters
arrayIn tableau de NBR_VAL valeurs
Returns
Moyenne calculée arrondie à l'entier en dessous
Definition at line 100 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
Referenced by main().
clignotteLED()
void clignotteLED (unsigned char nbrClignottement)
Fonction faisait clignotter la led à une fréquence de 2Hz pour un nombre de fois défini
Parameters
nbrClignottement nombre de fois que la LED doit s'allumer
Definition at line 113 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
Referenced by main().
main()
int main (void)
Definition at line 30 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
References bubbleSort(), calculMoyenne(), clignotteLED(), NBR_VAL, trouveMax(), and trouveMin().
sommeVal()
unsigned int sommeVal (unsigned char arrayIn[])
Fonction calculant la somme de toutes les valeurs d'un tableau
Parameters
arrayIn tableau de NBR_VAL valeurs
Returns
somme des valeurs du tableau
Definition at line 154 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
trouveMax()
unsigned char trouveMax (unsigned char arrayIn[])
Fonction cherchant la valeur la plus grande d'un tableau
Parameters
arrayIn tableau de NBR_VAL valeurs
Returns
valeur max trouvée dans le tableau
Definition at line 81 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
Referenced by main().
trouveMin()
unsigned char trouveMin (unsigned char arrayIn[])
Fonction cherchant la valeur la plus petite d'un tableau
Parameters
arrayIn tableau de NBR_VAL valeurs
Returns
valeur min trouvée dans le tableau
Definition at line 62 of file TP4_Martin_Marguerat_Vincent_Schupbach.c.
Referenced by main().